# Airbnb Price Prediction

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

## Importing our dataset

In [3]:
data = pd.read_csv('airbnb_top_cities.csv') #importing the dataset
data.head() #display the first 5 rows of the dataset

C:\Users\admin\AppData\Local\Temp\ipykernel_18808\1124383373.py:1: DtypeWarning: Columns (4,17) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('airbnb_top_cities.csv') #importing the dataset

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,city,scrape_date
0,13913,Holiday London DB Room Let-on going,54730,Alina,NaN,Islington,51.56861,-0.11270,Private room,70.0,1,55,2025-08-21,0.30,2,331,10,NaN,London,2026-03-29
1,15400,Bright Chelsea Apartment. Chelsea!,60302,Philippa,NaN,Kensington and Chelsea,51.48780,-0.16813,Entire home/apt,149.0,4,97,2025-04-05,0.51,1,199,1,NaN,London,2026-03-29
2,17402,Very Central Modern 3-Bed/2 Bath By Oxford St W1,67564,Liz,NaN,Westminster,51.52195,-0.14094,Entire home/apt,411.0,3,56,2024-02-19,0.32,2,80,0,NaN,London,2026-03-29
3,24328,Battersea live/work artist house,41759,Joe,NaN,Wandsworth,51.47072,-0.16266,Entire home/apt,NaN,7,95,2025-07-05,0.53,1,294,1,NaN,London,2026-03-29
4,36274,Bright 1 bedroom apt off brick lane in Shoreditch,133271,Hendryks,NaN,Tower Hamlets,51.52322,-0.06979,Entire home/apt,210.0,5,15,2025-09-06,0.09,2,323,6,NaN,London,2026-03-29

In [4]:
data.tail() #display the last 5 rows in the dataset

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,city,scrape_date
292797,1480042219847997681,Rustica Cove—Heritage Escape by Manly’s Shores,347608321,Calyn,NaN,Manly,-33.801750,151.288800,Entire home/apt,NaN,2,1,2025-08-24,1.00,16,309,1,PID-STRA-80839,Sydney,2026-03-29
292798,1480050997732404756,Modern Family Home In Paddington - 3 bedrooms,16026854,Tracey McArdle Exclusive Properties,NaN,Woollahra,-33.879040,151.227080,Entire home/apt,NaN,21,0,NaN,NaN,55,124,0,PID-STRA-79621,Sydney,2026-03-29
292799,1480052704340595354,Top Floor APT in heart of City,21151187,John,NaN,Sydney,-33.874723,151.223031,Entire home/apt,NaN,2,1,2025-08-26,1.00,22,0,1,PID-STRA-39071,Sydney,2026-03-29
292800,1480144278899031973,Two-bedroom standalone townhouse,711457600,Xuemei,NaN,Sydney,-33.917365,151.206906,Entire home/apt,NaN,1,10,2025-09-12,9.37,1,143,10,Exempt,Sydney,2026-03-29
292801,1480493397212908710,Central Burwood 2Beds | Walk to Westfield & Train,659806489,Leslie,NaN,Burwood,-33.878420,151.099180,Entire home/apt,NaN,1,4,2025-09-01,3.75,5,342,4,PID-STRA-81769,Sydney,2026-03-29

In [5]:
data.columns #display the columns in the dataset

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license', 'city',
       'scrape_date'],
      dtype='object')

In [6]:
data.dtypes #display the datatypes of each column

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                             float64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
number_of_reviews_ltm               int64
license                            object
city                               object
scrape_date                        object
dtype: object

In [7]:
data.info() #display info about the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 292802 entries, 0 to 292801
Data columns (total 20 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              292802 non-null  int64
 1   name                            292802 non-null  object
 2   host_id                         292802 non-null  int64
 3   host_name                       292712 non-null  object
 4   neighbourhood_group             19410 non-null   object
 5   neighbourhood                   292802 non-null  object
 6   latitude                        292802 non-null  float64
 7   longitude                       292802 non-null  float64
 8   room_type                       292802 non-null  object
 9   price                           139950 non-null  float64
 10  minimum_nights                  292802 non-null  int64
 11  number_of_reviews               292802 non-null  int64
 12  last_review                     226437 non-null  object
 13  reviews_per_month               226437 non-null  float64
 14  calculated_host_listings_count  292802 non-null  int64
 15  availability_365                292802 non-null  int64
 16  number_of_reviews_ltm           292802 non-null  int64
 17  license                         139853 non-null  object
 18  city                            292802 non-null  object
 19  scrape_date                     292802 non-null  object
dtypes: float64(4), int64(7), object(9)
memory usage: 44.7+ MB

In [9]:
data.describe() #display a statistical summary of the data

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm
count,2.928020e+05,2.928020e+05,292802.000000,292802.000000,1.399500e+05,292802.000000,292802.000000,226437.000000,292802.000000,292802.000000,292802.000000
mean,6.925516e+17,2.169006e+08,40.009043,21.583817,6.042208e+02,18.515328,31.822187,1.169245,21.022343,162.651423,7.942511
std,5.785082e+17,2.219687e+08,21.677901,43.996214,7.403676e+03,65.016518,73.409545,1.535733,69.392336,139.492379,15.926128
min,2.737000e+03,1.662000e+03,-34.095680,-0.496760,4.000000e+00,1.000000,0.000000,0.010000,1.000000,0.000000,0.000000
25%,3.347211e+07,2.495756e+07,41.878008,-0.066950,9.400000e+01,1.000000,1.000000,0.200000,1.000000,0.000000,0.000000
50%,8.724348e+17,1.180033e+08,48.866320,2.335690,1.630000e+02,2.000000,7.000000,0.630000,2.000000,155.000000,1.000000
75%,1.208697e+18,4.221622e+08,51.495854,12.463966,3.420000e+02,5.000000,29.000000,1.610000,9.000000,304.000000,9.000000
max,1.518168e+18,7.206394e+08,52.425120,151.340140,1.085147e+06,1125.000000,5097.000000,99.420000,816.000000,365.000000,1304.000000

In [10]:
data.shape #the dataset has 292802 rows and 20 coluumns

(292802, 20)